import sys

def to_uesc(s):
    return ''.join('\\u%04x' % ord(c) for c in s)

js_def = to_uesc('我的消息')
js_red = to_uesc('❤️有人想你了，快去看看是谁吧')

out = []
out.append('<!-- Notification Bar -->')
out.append('<a href="notifications" style="text-decoration:none;display:block;">')
out.append('<div id="notifyBar" style="position:fixed;bottom:0;left:0;right:0;z-index:99999;background:rgba(20,20,40,0.92);text-align:center;padding:10px 12px;cursor:pointer;border-top:1px solid rgba(255,255,255,0.08);">')
out.append('  <span id="notifyBarText" style="color:#888;font-size:13px;">&#25105;&#30340;&#28040;&#24687;</span>')
out.append('</div>')
out.append('</a>')
out.append('<script>')
out.append('(function(){')
out.append('  var bar = document.getElementById("notifyBarText");')
out.append('  if (!bar) return;')
out.append('  var lastId = 0, resetTimer = null;')
out.append("  var MSG_DEF = '" + js_def + "';")
out.append("  var MSG_RED = '" + js_red + "';")
out.append('  function check() {')
out.append('    var x = new XMLHttpRequest();')
out.append('    x.open("GET", "notifications", true);')
out.append('    x.setRequestHeader("X-Requested-With", "XMLHttpRequest");')
out.append('    x.onload = function() {')
out.append('      if (x.status !== 200) return;')
out.append('      try {')
out.append('        var list = JSON.parse(x.responseText);')
out.append('        if (list.length && list[0].id > lastId) {')
out.append('          lastId = list[0].id;')
out.append('          if ((Date.now() - new Date(list[0].time).getTime()) < 300000) {')
out.append('            bar.textContent = MSG_RED;')
out.append('            bar.style.color = "#ff4466";')
out.append('            bar.style.fontWeight = "bold";')
out.append('            clearTimeout(resetTimer);')
out.append('            resetTimer = setTimeout(reset, 300000);')
out.append('          }')
out.append('        }')
out.append('      } catch(e) {}')
out.append('    };')
out.append('    x.send();')
out.append('  }')
out.append('  function reset() {')
out.append('    bar.textContent = MSG_DEF;')
out.append('    bar.style.color = "#888";')
out.append('    bar.style.fontWeight = "normal";')
out.append('  }')
out.append('  var init = new XMLHttpRequest();')
out.append('  init.open("GET", "notifications", true);')
out.append('  init.setRequestHeader("X-Requested-With", "XMLHttpRequest");')
out.append('  init.onload = function() {')
out.append('    if (init.status !== 200) return;')
out.append('    try {')
out.append('      var list = JSON.parse(init.responseText);')
out.append('      if (list.length) {')
out.append('        lastId = list[0].id;')
out.append('        var age = Date.now() - new Date(list[0].time).getTime();')
out.append('        if (age < 300000) {')
out.append('          bar.textContent = MSG_RED;')
out.append('          bar.style.color = "#ff4466";')
out.append('          bar.style.fontWeight = "bold";')
out.append('          clearTimeout(resetTimer);')
out.append('          resetTimer = setTimeout(reset, 300000 - age);')
out.append('        }')
out.append('      }')
out.append('    } catch(e) {}')
out.append('  };')
out.append('  init.send();')
out.append('  setInterval(check, 15000);')
out.append('})();')
out.append('</script>')

with open(sys.argv[1], 'w', encoding='ascii') as f:
    f.write('\n'.join(out))
print('Done')
